import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import vm from "node:vm";
const source = readFileSync(new URL("../../overlay.js", import.meta.url), "utf8");
const take = (start, end) => { const a = source.indexOf(start), b = source.indexOf(end, a); assert(a >= 0 && b > a); return source.slice(a, b); };
const context = vm.createContext({ Math, Number, Set, Map, JSON, Object, String });
vm.runInContext(`
  ${take("  const STARTER_STATIONS =", "  const ROUTE_MAX_DESTINATIONS =")}
  const GALAXY_MAX_COORDINATE = 7000;
  ${take("  const finite =", "  const verifiedPerfectCount =")}
  const state = {seen:{}, systems:{}, routePlanner:{destinations:[]}};
  const publicAtlas = {systems:[]};
  let changes = 0; const markDirty = () => changes++;
  ${take("  const DUST_STAR_VALUES =", "  const renderOperations =")}
`, context);
const run = code => vm.runInContext(code, context);
assert.equal(run("STARTER_STATIONS.every(s => dustNearestStarter(s.x,s.y).distance === 0)"), true);
assert.equal(run("dustNearestStarter(3501,3500).distance"), 10);
assert(Math.abs(run("dustNearestStarter(3501,3501).distance") - Math.sqrt(2)*10) < 1e-8);
assert.equal(run("dustNearestStarter(3700,3500).starter.name"), "Sun");
assert.equal(run("dustNearestStarter(6124,6124).starter.name"), "Antares");
assert.equal(run("dustNearestStarter(3500,3500,2)"), null);
assert.equal(run("dustNearestStarter(null,3500)"), null);
assert.equal(run("dustCoordinate(true)"), null);
assert.equal(run("dustBaseValue(3700,3500,'O type',5).base"), 2180);
assert.equal(run("dustBaseValue(3700,3500,'O type',0).base"), 2080);
assert.equal(run("dustBaseValue(3700,3500,'unknown',5).base"), null);
assert.equal(run("dustBaseValue(3700,3500,'O type',null).base"), null);
assert.equal(run("dustBaseValue(3700,3500,'O type',null).bodyValue"), null);
assert.equal(run("dustBaseValue(3700,3500,'O type',true).base"), null);
assert.equal(run("dustBaseValue(3700,3500,'O type',-1).base"), null);
assert.equal(run("dustBaseValue(3700,3500,'O type',5.5).base"), null);
assert.equal(run("Object.values(DUST_STAR_VALUES).join(',')"), '300,280,200,150,80,50,40,30,20,10,10');
assert.equal(run("dustNearestStarter(4000,3500).distance - dustNearestStarter(3700,3500).distance"), 3000);
assert.equal(run("dustNearestStarter(1e6,1e6).distance > 1e6"), true, "Model itself must not cap distance rewards");
for(const value of ['null', "''", '0', '-1', '7001', '1.5', 'Infinity']) assert.equal(run(`dustCoordinate(${value})`), null);
assert.equal(run("dustCoordinate('7000')"), 7000);
assert.equal(run("dustViewport(1,7000,100).left"), 1);
assert.equal(run("dustViewport(1,7000,100).top"), 7000);
assert.equal(run("dustViewport(3500,3500,6999).right"), 7000);
assert.equal(run("dustPointFromFraction(dustViewport(3500,3500,6999),0,0).y"), 7000);
assert.equal(run("dustPointFromFraction(dustViewport(3500,3500,6999),1,1).y"), 1);
assert.equal(run("dustColor(0).join(',')"), '17,29,49');
assert.equal(run("dustColor(19000).join(',')"), '255,223,124');
run("captureDustSystem({coordinate_x:3700,coordinate_y:3500,star:'O type',name:'Test',bodies:[{},{},{},{},{}]})");
assert.equal(run("dustDetails(3700,3500).base"), 2180);
assert.equal(run("dustDetails(3700,3500).known"), true);
assert.equal(run("Object.keys(state.seen).length"), 0, "Dust metadata must not inflate personal seen totals");
assert.equal(run("Object.keys(state.systems).length"), 0, "Dust metadata must not pollute perfect nodes");
run("captureDustSystem({coordinate_x:3700,coordinate_y:3500,bodies:[{},{},{},{},{}]})");
assert.equal(run("dustDetails(3700,3500).star"), 'O type', "Partial journal row must retain known star");
assert.equal(run("changes"), 1, "Repeated unchanged capture must not churn persistence");
run("captureDustSystem({coordinate_x:3701,coordinate_y:3500,coordinate_z:2,star:'O type',bodies:[]})");
assert.equal(run("dustCatalog.size"), 1);
assert.equal(run("dustDetails(4700,4700).known"), false);
run("publicAtlas.systems=[{x:4700,y:4700}]");
assert.equal(run("dustDetails(4700,4700).known"), true);
assert.equal(run("dustDetails(4700,4700).base"), null, "A perfect-node record is not a full body count");
run("for(let x=1;x<=6500;x++) captureDustSystem({coordinate_x:x,coordinate_y:1,star:'M type',bodies:[]});");
assert.equal(run("dustCatalog.size"), 6000);
run("const persisted=[...dustCatalog]; dustCatalog.clear(); restoreDustCatalog(persisted);");
assert.equal(run("dustCatalog.size"), 6000);
assert.equal(run("dustDetails(6500,1).star"), 'M type');
assert(!/\b(?:fetch|XMLHttpRequest|WebSocket)\b/.test(take("  const DUST_STAR_VALUES =", "  const renderOperations =")), "Heatmap must not make network requests");
assert(source.includes('data-tab="dust"'));
console.log("Dust heatmap tests passed: formula, all nine starters, 10 LY units, star/body validation, unknown/known distinction, viewport bounds, persistence cap, and no network calls.");
